apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-record-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-record-frontend
  template:
    metadata:
      labels:
        app: health-record-frontend
    spec:
      containers:
      - name: backend
        image: ghcr.io/iku000888/health-record-frontend:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-record-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-record-api
  template:
    metadata:
      labels:
        app: health-record-api
    spec:
      containers:
      - name: backend
        image: ghcr.io/iku000888/health-record-api:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: CORS_ALLOW_ORIGIN
            value: http://localhost:8080
          - name: DB_HOST
            value: postgres-service
          - name: _DANGEROUSLY_ENABLE_PACT_SETUP
            value: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: your_username
            - name: POSTGRES_PASSWORD
              value: your_password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: health-record-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: health-record-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort