name: Build Uberjar

on:
  push:
    branches: [main]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          lein: 2.9.1                  # Leiningen
          # bb: 0.7.8                    # Babashka
          # clj-kondo: 2022.05.31        # Clj-kondo
          # cljfmt: 0.10.2               # cljfmt
          # cljstyle: 0.15.0             # cljstyle
          # cmd-exe-workaround: 'latest' # Replaces `clojure` with `deps.clj` on Windows
          # zprint: 1.2.3                # zprint

      - name: Uberjar
        working-directory: ./health-record-app
        run: lein uberjar

      - uses: actions/upload-artifact@v3
        with:
          name: ubarjar
          path: health-record-app/target/health-record-app-0.1.0-SNAPSHOT-standalone.jar

      # Optional step:
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          # key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          key: cljdeps-${{ hashFiles('health-record-app/project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-
