name: Create and publish a Docker image

on:
  workflow_run:
    workflows: ["Build Uberjar"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: health-record-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: uberjar
          path: health-record-app/target/health-record-app-0.1.0-SNAPSHOT-standalone.jar
